// Code generated by Kitex v0.4.4. DO NOT EDIT.

package feedservice

import (
	feed "Simple-Douyin/cmd/feed/kitex_gen/feed"
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return feedServiceServiceInfo
}

var feedServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "FeedService"
	handlerType := (*feed.FeedService)(nil)
	methods := map[string]kitex.MethodInfo{
		"Feed":             kitex.NewMethodInfo(feedHandler, newFeedServiceFeedArgs, newFeedServiceFeedResult, false),
		"Userid2VideoList": kitex.NewMethodInfo(userid2VideoListHandler, newFeedServiceUserid2VideoListArgs, newFeedServiceUserid2VideoListResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "feed",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func feedHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*feed.FeedServiceFeedArgs)
	realResult := result.(*feed.FeedServiceFeedResult)
	success, err := handler.(feed.FeedService).Feed(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFeedServiceFeedArgs() interface{} {
	return feed.NewFeedServiceFeedArgs()
}

func newFeedServiceFeedResult() interface{} {
	return feed.NewFeedServiceFeedResult()
}

func userid2VideoListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*feed.FeedServiceUserid2VideoListArgs)
	realResult := result.(*feed.FeedServiceUserid2VideoListResult)
	success, err := handler.(feed.FeedService).Userid2VideoList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFeedServiceUserid2VideoListArgs() interface{} {
	return feed.NewFeedServiceUserid2VideoListArgs()
}

func newFeedServiceUserid2VideoListResult() interface{} {
	return feed.NewFeedServiceUserid2VideoListResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Feed(ctx context.Context, req *feed.FeedRequest) (r *feed.FeedResponse, err error) {
	var _args feed.FeedServiceFeedArgs
	_args.Req = req
	var _result feed.FeedServiceFeedResult
	if err = p.c.Call(ctx, "Feed", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Userid2VideoList(ctx context.Context, req *feed.Userid2VideoListRequest) (r *feed.Userid2VideoListResponse, err error) {
	var _args feed.FeedServiceUserid2VideoListArgs
	_args.Req = req
	var _result feed.FeedServiceUserid2VideoListResult
	if err = p.c.Call(ctx, "Userid2VideoList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
