// Code generated by Kitex v0.4.4. DO NOT EDIT.

package publishservice

import (
	publish "Simple-Douyin/kitex_gen/publish"
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return publishServiceServiceInfo
}

var publishServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "PublishService"
	handlerType := (*publish.PublishService)(nil)
	methods := map[string]kitex.MethodInfo{
		"PublishAction":   kitex.NewMethodInfo(publishActionHandler, newPublishServicePublishActionArgs, newPublishServicePublishActionResult, false),
		"PublishList":     kitex.NewMethodInfo(publishListHandler, newPublishServicePublishListArgs, newPublishServicePublishListResult, false),
		"PublishIds2List": kitex.NewMethodInfo(publishIds2ListHandler, newPublishServicePublishIds2ListArgs, newPublishServicePublishIds2ListResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "publish",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func publishActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*publish.PublishServicePublishActionArgs)
	realResult := result.(*publish.PublishServicePublishActionResult)
	success, err := handler.(publish.PublishService).PublishAction(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPublishServicePublishActionArgs() interface{} {
	return publish.NewPublishServicePublishActionArgs()
}

func newPublishServicePublishActionResult() interface{} {
	return publish.NewPublishServicePublishActionResult()
}

func publishListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*publish.PublishServicePublishListArgs)
	realResult := result.(*publish.PublishServicePublishListResult)
	success, err := handler.(publish.PublishService).PublishList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPublishServicePublishListArgs() interface{} {
	return publish.NewPublishServicePublishListArgs()
}

func newPublishServicePublishListResult() interface{} {
	return publish.NewPublishServicePublishListResult()
}

func publishIds2ListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*publish.PublishServicePublishIds2ListArgs)
	realResult := result.(*publish.PublishServicePublishIds2ListResult)
	success, err := handler.(publish.PublishService).PublishIds2List(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPublishServicePublishIds2ListArgs() interface{} {
	return publish.NewPublishServicePublishIds2ListArgs()
}

func newPublishServicePublishIds2ListResult() interface{} {
	return publish.NewPublishServicePublishIds2ListResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) PublishAction(ctx context.Context, req *publish.PublishActionRequest) (r *publish.PublishActionResponse, err error) {
	var _args publish.PublishServicePublishActionArgs
	_args.Req = req
	var _result publish.PublishServicePublishActionResult
	if err = p.c.Call(ctx, "PublishAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PublishList(ctx context.Context, req *publish.PublishListRequest) (r *publish.PublishListResponse, err error) {
	var _args publish.PublishServicePublishListArgs
	_args.Req = req
	var _result publish.PublishServicePublishListResult
	if err = p.c.Call(ctx, "PublishList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PublishIds2List(ctx context.Context, req *publish.Ids2ListRequest) (r *publish.Ids2ListResponse, err error) {
	var _args publish.PublishServicePublishIds2ListArgs
	_args.Req = req
	var _result publish.PublishServicePublishIds2ListResult
	if err = p.c.Call(ctx, "PublishIds2List", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
